In [2]:
import pandas as pd

# Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
  - оценка 2 и меньше - низкий рейтинг
  - оценка 4 и меньше - средний рейтинг
  - оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [17]:
def rating_classification(inp):                                 #создаем функцию по условиям задачи
    if inp <= 2:
        return 'low'
    if inp <= 4:
        return 'medium'
    else:
        return 'hight'

rating = pd.read_csv('ratings.csv')                             #считываем исходный файл
rating['class'] = rating.rating.apply(rating_classification)    #применяем функцию к столбцу rating исходной таблицы и создаем новый столбец class с результатами работы функции
rating.head(10)

   userId  movieId  rating   timestamp   class
0       1       31     2.5  1260759144  medium
1       1     1029     3.0  1260759179  medium
2       1     1061     3.0  1260759182  medium
3       1     1129     2.0  1260759185     low
4       1     1172     4.0  1260759205  medium
5       1     1263     2.0  1260759151     low
6       1     1287     2.0  1260759187     low
7       1     1293     2.0  1260759148     low
8       1     1339     3.5  1260759125  medium
9       1     1343     2.0  1260759131     low

# Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

Результат классификации запишите в отдельный столбец region.

In [34]:
keywords = pd.read_csv('keywords.csv')       #считываем исходный файл

geo_data = {                                 #параметры поиска по городам с привязкой к региону
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}
keywords.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [33]:
def region_search(inp):                           #создаем функцию для поиска
    for region in geo_data:                       #цикл по ключевым словам исходного словаря geo_data
        for city in geo_data[region]:             #цикл по городам исходного словаря geo_data[ключ словаря]
            if city in inp:                       # поиск городов в исходных данных 
                return region
    return 'undefined'

keywords['region'] = keywords['keyword'].apply(region_search) #применяем функцию к столбцу keyword исходной таблицы и создаем новый столбец region с результатами работы функции
keywords.region.value_counts()                      #подсчет уникальных значений по созданному столбцу region

undefined         99253
Центр               387
Северо-Запад        266
Дальний Восток       94
Name: region, dtype: int64